### ISSUE TITLE
Question: Has this library been ported to android or is there a similar looking library for android?

### ISSUE THREAD

**Issue by hu55a1n1** [arn00s/cariocamenu#13]
Firstly, thank you for an awesome library! Great work!
It would be great to have a similar library for android.

Has this library been ported to android or is there a similar looking library for android that you're aware of?

**Comment by zigzagg16** [comment]
Hi @Sufi-Al-Hussaini , thanks a lot for your feedback ! 👍 
Actually I am not aware of an Android equivalent, unfortunately
I'd like to port it to Android one day, but I'll need a lot of time for that 😄
