### ISSUE TITLE
Unknown error in the app after I did like example demo ?

### ISSUE THREAD

**Issue by Mohammed-Elias** [arn00s/cariocamenu#19]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[test.MainViewController cariocaMenuDidSelect:indexPath:]: unrecognized selector sent to instance 0x7ffa48e00be0'

this happen when ever I click on cell for the menu.

**Comment by zigzagg16** [comment]
Hi @Mohammed-Eliass , can you provide some sample code ?

**Comment by zigzagg16** [comment]
As I have no feedback, I'm closing the issue.
