### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by csjones** [arn00s/cariocamenu#2]
Would you be willing to add carthage support for this?

**Comment by zigzagg16** [comment]
Of course, I'll try to do it this weekend, I'll keep you updated!

**Comment by zigzagg16** [comment]
It will definitely take more time to add Carthage support, sorry about that. I need to convert the project to a framework, and I don't have so much time now to do it :)

**Comment by csjones** [comment]
No worries! :) Would it be easier to create a new framework target instead of converting?

**Comment by zigzagg16** [comment]
Hey csjones ! I finally made it :) Please give me feedback if it doesn't work for you !

**Comment by csjones** [comment]
Hey arn00s! It works :+1:
