### ISSUE TITLE
Many items in menu blows the app.

### ISSUE THREAD

**Issue by anelad** [arn00s/cariocamenu#20]
[x] There is no issue opened before about this.
[x] Issue is reproduceable in demo project.

### What did I do?
- Downloaded the demo project.
- Wanted to check how it works with many menu items, so I copy pasted default menus 3 times. (4 times menu items at the end.) Change nothing else.
- Ran on iPhone 6s with iOS 11.2.1

### What happened?
- `CaroicaGestureManager.swift` file,  `panned(yLocation:, edge:, state:, fromGesture:)`method, line `76`
- `let yRange: ClosedRange<CGFloat> = 20.0...frameHeight - container.menuHeight`
- Fatal error occured: `Thread 1: Fatal error: Can't form Range with upperBound < lowerBound`.
- Reason: With 4x menu items, container.menuHeight became greater than frameHeight I suppose.

**Comment by zigzagg16** [comment]
Hi @anelad, thanks a lot for reporting! I’ll investigate your 2 issues as soon as my laptop is back from repair!

**Comment by anelad** [comment]
Thank you @arn00s, if it gonna take a while, please let me know, because if I am gonna use your menu, I don't have much time to wait unfortunately. So I can check deeply, fix if I can and send a pull request.

**Comment by zigzagg16** [comment]
Hey @anelad, unfortunately they said between one or 2 weeks, so it won’t be before Saturday 20 for sure 😔 feel free to open a PR!

**Comment by anelad** [comment]
@arn00s, Since it is a `zero-tap` menu, there is no room to scroll more than the screen size, so menu content size can't be -at least shouldn't be- greater than the screen size with the current pan gesture settings.

I will try to create pan gesture effect multiplier, which changes according to screenHeight - menuHeight ratio.

Something like:
```
panMultiplier = screenHeight > menuHeight ? 1 : menuHeight/screenHeight
```

**Comment by zigzagg16** [comment]
Hey @anelad , sorry but the repair is taking more time than announced. Have you solved it ? Having a look at the code, you could check that frameHeight-menuHeight > 20.0, otherwise have a closedRange of 20.0...frameHeight. The menu should still be usable (to test, I cannot confirm)

**Comment by anelad** [comment]
Hi @arn00s. Sorry for the late response. I couldn’t solve the issue. I believe it is about the offset calculation approach that you used. BTW, I created my own zero-tap menu, with specific needs for my app. But with a different offset calculation too. I can share it if you want. It’s working with 1 to 400 menu items.

**Comment by MaeseppTarvo** [comment]
@anelad can you share it?

**Comment by anelad** [comment]
@MaeseppTarvo, yes I can but I’m moving my house now and my menu project is not finished yet. So give me 1 or 2 week(s) please.

**Comment by anelad** [comment]
@MaeseppTarvo, my project is private, and it will be until I finish it, but I'm adding you as a collaborator. Sorry for the late response :(

**Comment by zigzagg16** [comment]
Hey @anelad , the issue was finally fixed :)
By the way, can you also invite me in your project ? I'm interested to know more !
