### ISSUE TITLE
Menu uses too much memory

### ISSUE THREAD

**Issue by anelad** [arn00s/cariocamenu#21]
### What did I do? 
- Downloaded the demo project and ran it on iPhone 6s with iOS 11.2.1 without any modification.
- Travelled between content pages many times. (Not to be a prick, just to present the menu to my collegues.)

### What happened?
- Memory usage gone beyond 150 MB.

### Any ideas?
I traced the memory usage while travelling between pages. I saw 2 things.
- WebView data is not released when you go to another page.
- MapView data is released but not completely when you go to another page.

I don't know if these are issues about the menu, or something else, but false alarm better than no alarm :]

**Comment by zigzagg16** [comment]
Hey @anelad , thanks for reporting. This seems to be related with the demo only. I'll have a look.

**Comment by zigzagg16** [comment]
this has been fixed in the demo app !

**Comment by zigzagg16** [comment]
By the way, the Map memory may still increase in the simulator.
On device, everything looks fine.
