### ISSUE TITLE
Dismiss Viewcontroller

### ISSUE THREAD

**Issue by MaeseppTarvo** [arn00s/cariocamenu#22]
Hey, I am trying to dismiss presented `ViewController` but instead on dismissing, it goes to Carioca's default viewcontroller`ViewController`. My initial `ViewController` is `UINavigationController` but I do not think that is an issue. Is it a bug or I am stupid?

And this is how I present:

```
let emptyViewController = EmptyViewViewController.fromStoryboard()
present(emptyViewController, animated: true, completion: nil)
```

**Comment by zigzagg16** [comment]
Hi @MaeseppTarvo , not sure I understood, as you're speaking of dismiss, but your code is showing some presentation code. Can you give more info ?
