### ISSUE TITLE
icon is too big

### ISSUE THREAD

**Issue by MaeseppTarvo** [arn00s/cariocamenu#23]
Hey! I am trying to apply icon instead of emoji but the problem is that the icon is way too big. This is how I add icon:

```
var menuItems: [CariocaMenuItem] = [
        CariocaMenuItem("Test1", .icon(UIImage(named: "test1Icon")!)),
        CariocaMenuItem("Test2", .icon(UIImage(named: "test2Icon")!))
    ]
```

This is the output:

<img width="68" alt="screen shot 2018-03-13 at 02 05 07" src="https://user-images.githubusercontent.com/8416295/37315557-f86529ec-2662-11e8-9861-f31f6ec75aeb.png">

My icon is 15x15

**Comment by zigzagg16** [comment]
Hi @MaeseppTarvo , I would suggest you resize your icon, or use a custom indicator : 

`class CariocaCustomIndicatorView: UIView, CariocaIndicatorConfiguration`
