### ISSUE TITLE
Rotation Bug

### ISSUE THREAD

**Issue by emptyway** [arn00s/cariocamenu#4]
The library doesn't handle well when rotating the screen.

Steps to reproduce
- In portrait mode (Unlock rotation)
- Open the menu
- Scroll to About
- Open the menu again
- Rotate to landscape

Expected result
- The Menu Centered in landscape mode 

Actual Results
- The Menu is half visible. (If you play it a couple of time, the menu button will disappear)

**Comment by zigzagg16** [comment]
Hi @simonlinj , rotation is not supported yet, nut I plan to add it in a future release.

**Comment by zigzagg16** [comment]
Hey @simonlinj , it finally has been fixed in v 2.0 !
